// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function CreateLocalSession(arg1) {
  return window['go']['main']['App']['CreateLocalSession'](arg1);
}

export function CreateSSHSession(arg1) {
  return window['go']['main']['App']['CreateSSHSession'](arg1);
}

export function CreateTelnetSession(arg1) {
  return window['go']['main']['App']['CreateTelnetSession'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveProfiles(arg1) {
  return window['go']['main']['App']['SaveProfiles'](arg1);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}
