// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CreateSessionRequest {
    shell: string;
    cwd: string;
    cols: number;
    rows: number;
}

export function CreateLocalSession(arg1: CreateSessionRequest): Promise<string>;

export function SendInput(arg1: string, arg2: string): Promise<void>;

export function ResizeSession(arg1: string, arg2: number, arg3: number): Promise<void>;

export function CloseSession(arg1: string): Promise<void>;
