// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateLocalSession(arg1) {
    return window['go']['main']['App']['CreateLocalSession'](arg1);
}

export function SendInput(arg1, arg2) {
    return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function ResizeSession(arg1, arg2, arg3) {
    return window['go']['main']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function CloseSession(arg1) {
    return window['go']['main']['App']['CloseSession'](arg1);
}

export function GetConfig() {
    return window['go']['main']['App']['GetConfig']();
}

export function SaveConfig(arg1) {
    return window['go']['main']['App']['SaveConfig'](arg1);
}

export function GetConfigPath() {
    return window['go']['main']['App']['GetConfigPath']();
}
