// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function CreateLocalSession(arg1:main.CreateSessionRequest):Promise<string>;

export function CreateSSHSession(arg1:main.SSHSessionRequest):Promise<string>;

export function CreateTelnetSession(arg1:main.TelnetSessionRequest):Promise<string>;

export function GetConfig():Promise<config.Document>;

export function GetConfigPath():Promise<string>;

export function GetProfiles():Promise<Array<Record<string, any>>>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveConfig(arg1:config.Document):Promise<void>;

export function SaveProfiles(arg1:Array<Record<string, any>>):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;
